import tempfile
import unittest
from pathlib import Path

from docketry.envelope import Envelope
from docketry.gates.notice import NoticeParser
from docketry.notices import (
    AdapterError, builtin_adapters, load_adapters_file, parse, stack,
)


def env(from_addr, subject, body):
    return Envelope(
        message_id="m", from_addr=from_addr, to=[], cc=[], date="",
        subject=subject, body_text=body, attachments=[],
        raw_sha256="e" * 64, source="t", fetched_at="now",
    )


EPORTAL = env(
    "eservice@myflcourtaccess.com",
    "SERVICE OF COURT DOCUMENT 562026CA001234",
    "Notice of Service of Court Documents\n"
    "Case Number: 562026CA001234\n"
    "Court: Nineteenth Judicial Circuit in and for St. Lucie County\n"
    "Case Style: DOE v. ACME INSURANCE COMPANY\n"
    "Document: Motion to Compel Discovery\n"
    "Document: Notice of Hearing\n"
    "Served: kelly@examplefirm.com\n"
    "Served: oc@defensefirm.com\n",
)

NEF = env(
    "ecf_bounces@flsd.uscourts.gov",
    "Activity in Case 2:26-cv-01234-XYZ Doe v. Acme Insurance Order on Motion",
    "This is an automatic e-mail message generated by the CM/ECF system.\n"
    "Document Number: 45\n"
    "Docket Text: ORDER granting in part Motion to Compel.\n"
    "https://ecf.flsd.uscourts.gov/doc1/0511122233\n",
)

JACS = env(
    "noreply@circuit19.org",
    "Hearing Scheduled",
    "Judicial Automated Calendaring System\n"
    "Case Number: 562026CA001234\n"
    "Hearing Date: 09/15/2026\n"
    "Time: 10:30 AM\n"
    "Judge: Hon. Example Judge\n"
    "Matter: Motion to Compel (15 min)\n",
)

RECEIPT = env(
    "no-reply@efilingmail.tylertech.cloud",
    "Filing Accepted for Case 562026CA001234",
    "Envelope Number: 88123456\n"
    "Case Number: 562026CA001234\n"
    "Filing Description: Response to Motion to Strike\n",
)

PLAIN = env("client@gmail.com", "question about my case", "hi, quick question")


class TestBuiltinAdapters(unittest.TestCase):
    def test_eportal(self):
        r = parse(EPORTAL, builtin_adapters())
        self.assertEqual(r.adapter, "fl-eportal-service")
        self.assertEqual(r.notice_type, "service_notice")
        self.assertEqual(r.fields["case_number"], "562026CA001234")
        self.assertEqual(len(r.fields["documents"]), 2)
        self.assertEqual(len(r.fields["served"]), 2)
        self.assertEqual(r.missing, [])

    def test_pacer_nef_captures_link_without_fetching(self):
        r = parse(NEF, builtin_adapters())
        self.assertEqual(r.adapter, "pacer-nef")
        self.assertEqual(r.fields["case_number"], "2:26-cv-01234-XYZ")
        self.assertEqual(r.fields["document_number"], "45")
        self.assertTrue(r.fields["document_link"].startswith("https://ecf.flsd.uscourts.gov/"))

    def test_jacs_hearing(self):
        r = parse(JACS, builtin_adapters())
        self.assertEqual(r.adapter, "jacs-hearing")
        self.assertEqual(r.notice_type, "hearing_notice")
        self.assertEqual(r.fields["hearing_date"], "09/15/2026")
        self.assertEqual(r.fields["hearing_time"], "10:30 AM")

    def test_efile_receipt(self):
        r = parse(RECEIPT, builtin_adapters())
        self.assertEqual(r.adapter, "efile-receipt")
        self.assertEqual(r.fields["envelope_number"], "88123456")
        self.assertEqual(r.fields["status"], "Accepted")

    def test_subject_words_cannot_satisfy_label_fields(self):
        # "SERVICE OF COURT DOCUMENT" in the subject must not populate
        # the 'court' field; labels only match at line starts.
        r = parse(EPORTAL, builtin_adapters())
        self.assertTrue(r.fields["court"].startswith("Nineteenth"))

    def test_plain_mail_no_match(self):
        self.assertIsNone(parse(PLAIN, builtin_adapters()))

    def test_required_miss_is_loud(self):
        broken = env(
            "eservice@myflcourtaccess.com",
            "SERVICE OF COURT DOCUMENT",
            "totally new template with no fields",
        )
        r = parse(broken, builtin_adapters())
        self.assertEqual(r.missing, ["case_number"])


class TestFirmAdapters(unittest.TestCase):
    def _load(self, text):
        with tempfile.TemporaryDirectory() as tmp:
            p = Path(tmp) / "adapters.toml"
            p.write_text(text)
            return load_adapters_file(p)

    def test_example_file_loads_and_overrides(self):
        adapters = load_adapters_file("examples/adapters.toml")
        self.assertEqual(adapters[0].name, "st-lucie-ja-hearing")
        e = env("ja@stlucieclerk.com", "Hearing Set",
                "Hearing Date: 10/01/2026\nTime: 9:00 AM\nJudge: Hon. X\nCase No: 562026CA000001")
        full = adapters + builtin_adapters()
        r = parse(e, full)
        self.assertEqual(r.adapter, "st-lucie-ja-hearing")

    def test_bad_notice_type_refused(self):
        with self.assertRaises(AdapterError):
            self._load('[[adapter]]\nname="x"\nnotice_type="magic"\n'
                       '[adapter.match]\nfrom="@a.com"\n[adapter.fields]\nd="(x)"')

    def test_pattern_without_group_refused(self):
        with self.assertRaises(AdapterError):
            self._load('[[adapter]]\nname="x"\nnotice_type="hearing_notice"\n'
                       '[adapter.match]\nfrom="@a.com"\n[adapter.fields]\nd="nogroup"')

    def test_required_without_pattern_refused(self):
        with self.assertRaises(AdapterError):
            self._load('[[adapter]]\nname="x"\nnotice_type="hearing_notice"\nrequired=["ghost"]\n'
                       '[adapter.match]\nfrom="@a.com"\n[adapter.fields]\nd="(x)"')

    def test_no_match_rules_refused(self):
        with self.assertRaises(AdapterError):
            self._load('[[adapter]]\nname="x"\nnotice_type="hearing_notice"\n[adapter.fields]\nd="(x)"')


class TestNoticeGate(unittest.TestCase):
    def test_gate_info_on_clean_parse(self):
        findings = NoticeParser().check(EPORTAL, {})
        self.assertEqual(len(findings), 1)
        self.assertEqual(findings[0].severity, "info")

    def test_gate_fails_loud_on_template_drift(self):
        broken = env("eservice@myflcourtaccess.com", "SERVICE OF COURT DOCUMENT", "new template")
        findings = NoticeParser().check(broken, {})
        severities = [f.severity for f in findings]
        self.assertIn("fail", severities)

    def test_gate_silent_on_ordinary_mail(self):
        self.assertEqual(NoticeParser().check(PLAIN, {}), [])


if __name__ == "__main__":
    unittest.main()
